#!/usr/bin/env bash
# Installs nginx with the following configs:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried

sudo apt-get update
sudo apt-get install -y nginx-full

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
