#!/usr/bin/env bash
# Dislplays "Best School" 10 times. However,
#+ in the 9th time it also displays "Hi".

count=0

while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	(( count++ ))
done
