#!/usr/bin/env bash
# Displays "Best School" 10 times, but
# "bad luck" and "good luck" in some iterations.

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
